### ISSUE TITLE
Use toggle instead of checkbox

### ISSUE THREAD

**Issue by bjarnef** [Novicell/Novicell.Umbraco.OEmbed#11]
It noticed a traditional checkbox currently is used here: https://github.com/Novicell/Novicell.Umbraco.OEmbed/blob/main/src/Novicell.Umbraco.OEmbed/App_Plugins/Novicell.OEmbed/oembed.editor.html#L39

It can use `<umb-checkbox>` or `<umb-toggle>` component instead. In this case it would probably use a toggle as it is a setting.

In Umbraco core: https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/embed/embed.html#L48

**Comment by soreng** [comment]
We actually never set supportsDimensions anywhere, so that section is never shown. I think it was something we "borrowed" from the original view found in Umbraco.
