### ISSUE TITLE
Use button elements

### ISSUE THREAD

**Issue by bjarnef** [Novicell/Novicell.Umbraco.OEmbed#12]
I noticed these "buttons" using anchor elements, but should Really use `<button type="button">` instead to be accessible: https://github.com/Novicell/Novicell.Umbraco.OEmbed/blob/main/src/Novicell.Umbraco.OEmbed/App_Plugins/Novicell.OEmbed/oembed.propertyeditor.html#L9-L14

The same is valid for this button, which then doesn't need `prevent-default` directive:
https://github.com/Novicell/Novicell.Umbraco.OEmbed/blob/main/src/Novicell.Umbraco.OEmbed/App_Plugins/Novicell.OEmbed/oembed.propertyeditor.html#L19-L21

Example from Umbraco core:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/prevalueeditors/multivalues.html#L17

**Comment by jannikanker** [comment]
Could it even be a umb-button directive thingy? https://our.umbraco.com/apidocs/v8/ui/#/api/umbraco.directives.directive:umbButton

**Comment by bjarnef** [comment]
Sure, but `<button>` element should be suffie
cient. I would probably use `<umb-button>` if I needed the `icon` and/or the `state` attibutes.

**Comment by soreng** [comment]
Right now it is build as a mix of a media picker and the link picker. The buttons have been changed, but I don't think we should add icons on the button as things are right now.
