### ISSUE TITLE
Method not found: 'System.String Umbraco.Extensions.LocalizedTextServiceExtensions.Localize(Umbraco.Cms.Core.Services.ILocalizedTextService, System.String, System.String,

### ISSUE THREAD

**Issue by jkulker** [Novicell/Novicell.Umbraco.OEmbed#19]
With the new release candidate inserting vimeo url results in error

Method not found: 'System.String Umbraco.Extensions.LocalizedTextServiceExtensions.Localize(Umbraco.Cms.Core.Services.ILocalizedTextService, System.String, System.String,

**Comment by jkulker** [comment]
Probally related to: https://github.com/umbraco/Umbraco-CMS/issues/10927

**Comment by soreng** [comment]
thx for reporting this @jkulker 

I did some work before the week-end, but didn't have a chance to release it until now -- there is a new version out https://www.nuget.org/packages/Novicell.Umbraco.OEmbed/1.0.0-rc002.1
