### ISSUE TITLE
Component shouldn't be self-closing

### ISSUE THREAD

**Issue by bjarnef** [Novicell/Novicell.Umbraco.OEmbed#8]
I noticed the code is using `<novicell-oembed-preview />` which will cause issues in newer versions of Angular, mainly with any following sibling elements.
https://github.com/Novicell/Novicell.Umbraco.OEmbed/blob/main/src/Novicell.Umbraco.OEmbed/App_Plugins/Novicell.OEmbed/oembed.editor.html#L24

So it should be similar to web comments using a end-closing tag, e.g. `<novicell-oembed-preview></novicell-oembed-preview>`.

Actually only a limited set og HTML elements should be self-closed like br, hr, img, input, etc.

**Comment by soreng** [comment]
thx @bjarnef 

A review from you means a lot :)

**Comment by bjarnef** [comment]
You are welcome @soreng 😎🤓🏆🍻
